oxwalldb:
  image: mysql:5.6
  volumes:
    - ./mysql/runtime:/var/lib/mysql
  env_file:
    - ./.env

oxwallweb:
  image: maxdev123/oxwall-dev
  links:
    - oxwalldb
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./data:/var/www/html
    - ./external:/etc/apache2/external
  env_file:
    - ./.env

oxwallcron:
  image: maxdev123/oxwall-dev
  command: cron -f
  volumes:
    - ./crontab:/etc/cron.d/oxwall
  volumes_from:
    - oxwallweb
  links:
    - oxwalldb
